# Generated by Django 4.2 on 2023-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_files',
            name='files',
            field=models.FileField(upload_to='./media/files'),
        ),
    ]
